[package]
name = "GhostPay"
version = "1.0.0"
authors = ["GhostPay"]

[addresses]
ghostpay = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
